# Welcome to Jekyll!

# Select a theme
theme: jekyll-theme-minimal

# Site-wide title (appears in browser tab)
title: Dayuan Wang

# Site-wide description
description: PhD Student in Biostatistics at the University of Florida.
